version: '3'
services:
  course-search:
    image: louieh/course-search
    container_name: course-search
    #    ports:
    #      - "5001:5001"
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - CUSTOM_SEARCH_KEY=${CUSTOM_SEARCH_KEY}
      - CUSTOM_SEARCH_UTD_ID=${CUSTOM_SEARCH_UTD_ID}
      - CUSTOM_SEARCH_FAKECOURSEBOOK_ID=${CUSTOM_SEARCH_FAKECOURSEBOOK_ID}
      - FLASK_CONFIG=production
    #    volumes:
    #      - $PWD/log/datainsert.log:/log/datainsert.log
    command: gunicorn -w 4 -b :9000 --log-level debug course_search:app
    depends_on:
      - redis
      - mongo
      - nginx

  update_data:
    image: louieh/course-search-update-data
    container_name: update_data
    restart: always
    environment:
      - UPDATE_INTERVAL=360
      - CONFIG_TYPE=production
      - UPDATE_FOR_SEARCH=True
      - UPDATE_FOR_GRAPH=False
      - UPDATE_FOR_SPEED=False
      - GRADUATE_LEVEL=True
      - SKIP=False
    command: python run.py -m # -s
    depends_on:
      - redis
      - mongo

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: /bin/sh -c "nginx -g 'daemon off;'"
    ports:
      - '80:80'

  mongo:
    image: mongo:4.4.0
    container_name: mongo
    restart: always
    #    ports:
    #      - "27017:27017"
    volumes:
      - $PWD/mongo/data:/data/db
      - $PWD/mongo/log:/var/log/mongodb/mongod.log

  redis:
    image: redis
    container_name: redis
    #    ports:
    #      - "6379:6379"
    volumes:
      - $PWD/redis:/data
    restart: always
